### ISSUE TITLE
Can you make so the bot can upload directly from rclone?

### ISSUE THREAD

**Issue by tmatzxzone** [XronTrix10/Telegram-Leecher#1]
Upload directly with rclone / local file from the colab with just directory not link

**Comment by XronTrix10** [comment]
> Upload directly with rclone / local file from the colab with just directory not link

The Local upload from colab via directory will be implemented soon 💥 Stay Tuned ! For more queries and suggestions, you can join our Telegram Channel and group

**Comment by tmatzxzone** [comment]
Featured added and work perfectly
