### ISSUE TITLE
Error!!!!!!!!

### ISSUE THREAD

**Issue by amr-brar** [XronTrix10/Telegram-Leecher#11]
├🤔 Reason » Can't Download from this link. Because:  [0;31mERROR: [0m [generic] Unable to download webpage: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007) (caused by CertificateVerifyError('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Link was https://download.filedownloadlink.xyz/455.mp4

**Comment by XronTrix10** [comment]
The site is not supported by ytdl. I will replace the ytdl with ytdlp module later, then try again this sites
