### ISSUE TITLE
Please support split videos as stream, not as zip

### ISSUE THREAD

**Issue by tuthanika** [XronTrix10/Telegram-Leecher#12]
Please support split videos (>2GB)  as stream, not as zip.

Ex: video.mkv  --> video-001.mkv & video-002.mkv

**Comment by XronTrix10** [comment]
Is it necessary to do so ? Splitting videos causes data loss and sometimes corruptions. Also it requires a lot time in splitting videos

**Comment by tuthanika** [comment]
Split video without re-encore (ffmpeg, mkvtoolnix), so the process is very fast and don't data loss. When needed, you can download it and then use mkvtoolnix to merge normally. I use bots like aria-mirror to do the same thing, it's ok

**Comment by Ash-codes18** [comment]
> Please support split videos (>2GB) as stream, not as zip.
> 
> Ex: video.mkv --> video-001.mkv & video-002.mkv

Yeah, this would be so much better.

**Comment by XronTrix10** [comment]
This issue is resolved by #46
