### ISSUE TITLE
Ability to change file extension 

### ISSUE THREAD

**Issue by cod-md** [XronTrix10/Telegram-Leecher#3]
There are some links that don't end with the file extension like this

[Link](https://rr1---sn-x5guiapo3uxax-cbfld.googlevideo.com/videoplayback?expire=1696593050&ei=OqAfZZvzGr-zx_APlJieoAs&ip=38.9.111.11&id=o-AM-77k_-5PBt5HQn6oqVbpP7lYl31OAnbGWq5HVWG-U2&itag=22&source=youtube&requiressl=yes&mh=0i&mm=31%2C29&mn=sn-x5guiapo3uxax-cbfld%2Csn-4wg7ln7k&ms=au%2Crdu&mv=m&mvi=1&pl=24&initcwndbps=582500&vprv=1&mime=video%2Fmp4&cnr=14&ratebypass=yes&dur=1792.208&lmt=1630625866783709&mt=1696571101&fvip=4&fexp=24007246&beids=24350018&c=ANDROID_TESTSUITE&txp=6211224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRAIgCGJUWlit7u_uRLIqvudTwoZ7QO1AW_8F46HBLP-p_dcCICTqMjTYPzGvTUCpneT1iacvp2tY-khbHr7-spEbGaqO&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgfg7N9ZgMbMm198sN_G2ju2i9ByQZDICw-bupqftZi88CIQCT-HrzUznRMZRSFEceX16iywDmo-Y-ryBK5ztMq06KCw%3D%3D) 

I hope you can add a feature to change file extension within the bot
Thanks ❤️

**Comment by XronTrix10** [comment]
## This [Commit](https://github.com/XronTrix10/Telegram-Leecher/commit/3fdac21907201681a4a408da128229702f7b5063#diff-0bed85d4cc08bca10cca97588f34abbe74202fc9b9b79722d7ac5d1cfddf4c68) Solved the File name issue. Now you can manually change the file name before downloading.

While entering Link, enter the new name within square brackets in new line. This way : 

<pre>https://demo_link_to_file.mp4
[new file name.mkv]</pre>
