### ISSUE TITLE
Video split not working 

### ISSUE THREAD

**Issue by pasindudilsan** [XronTrix10/Telegram-Leecher#49]
Video split feature not working for x265 videos and some large video files including x264 videos.
When uploading spilited videos it only uploads final part of video.

Please add timeout for torrent downloads.
When I add dead torrent bot not responding and need to restart again.
Waiting for multiple tasks feature 😍.

**Comment by XronTrix10** [comment]
Thanks for informing, I will look into it. Closing this issue as there is already another issue on it
